BEGIN;
--drop view "1".V_EXPORT_LEDGER;
drop view "1".V_ACCOUNT_NAME;
--drop view "1".V_REP_CHECK_TOTAL;
drop view "1".V_ACCOUNT;
drop view "1".V_COMMODITY;
drop view "1".V_MARKET;
drop view "1".V_TRADE;
drop view "1".V_RATE;
drop view "1".V_CURRENCY_EXCHANGE;
drop view "1".V_CURRENCY;
drop view "1".V_PARAMETER;
drop view "1".V_POOL;
drop view "1".V_EXPECTANCY;
drop view "1".V_TRADE_JOURNAL;
drop view "1".V_COMMODITY_TYPE;
drop view "1".V_CFD_GENERAL;
drop view "1".V_COMMODITY_INFO;
COMMIT;
